# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3cd476b10ac2cfe883ff44f6479cd5249ab3b754fecdf00ab2f7d0172a00bd6d30cffb3dc2df2d2857480bbd91d23cdfe4b7f6316eee97859e4581b6ba81d4f

test:
  secret_key_base: 1cb3bf00128ea0942cb081ad7fd3e8b7a66df46b537ca8cc3ca40cfb0f04195bc2e093e92532b4581bb4118fe9f1f23d53096253e3de6df5ac585cfbb788b429

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
